trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install robotframework
    pip install robotframework-seleniumlibrary
  displayName: 'Install Robot Framework and SeleniumLibrary'

- script: |
    robot --outputdir $(Build.ArtifactStagingDirectory)/TestReports --output report.xml piperobot.robot
  displayName: 'Execute Robot Framework tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/TestReports'
    artifactName: 'TestReports'
    publishLocation: 'pipeline'
  displayName: 'Publish Test Reports'